// Mock product data with realistic names and details
export const mockProducts = [
  {
    id: "game-1",
    title: "Elden Ring",
    description:
      "THE NEW FANTASY ACTION RPG. Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.",
    image: "/images/elden.png",
    price: 59.99,
    discount: 25,
    platform: "Steam",
    category: "games",
    publisher: "Bandai Namco",
    releaseDate: "2022-02-25",
    genres: ["Action", "RPG", "Open World"],
    rating: 4.8,
    sales: 12000000,
    features: ["Open World", "Multiplayer", "Controller Support"],
    images: [
      "/images/elden.png",
      "/images/elden-desc1.png",
      "/images/elden-desc2.png",
      "/images/elden-desc3.png",
      "/images/elden-desc4.png",
    ],
  },
  {
    id: "game-2",
    title: "Cyberpunk 2077",
    description:
      "An open-world, action-adventure RPG set in Night City, a megalopolis obsessed with power, glamour and body modification.",
    image: "/images/cyberpunk.png",
    price: 59.99,
    discount: 50,
    platform: "GOG",
    category: "games",
    publisher: "CD Projekt RED",
    releaseDate: "2020-12-10",
    genres: ["RPG", "Open World", "Sci-Fi"],
    rating: 3.9,
    sales: 18000000,
    features: ["Open World", "Single-player", "Story Rich"],
    images: [
      "/images/cyberpunk.png",
      "/images/cyberpunk-desc1.jpg",
      "/images/cyberpunk-desc2.jpg",
      "/images/cyberpunk-desc3.jpg",
      "/images/cyberpunk-desc4.jpg",
    ],
  },
  {
    id: "game-3",
    title: "Red Dead Redemption 2",
    description:
      "An epic tale of life in America's unforgiving heartland. The game's vast and atmospheric world also provides the foundation for a brand new online multiplayer experience.",
    image: "/images/rdr2.jpg",
    price: 59.99,
    discount: 40,
    platform: "Epic Games",
    category: "games",
    publisher: "Rockstar Games",
    releaseDate: "2019-11-05",
    genres: ["Action", "Adventure", "Open World"],
    rating: 4.9,
    sales: 45000000,
    features: ["Open World", "Multiplayer", "Story Rich"],
    images: [
      "/images/rdr2.jpg",
      "/images/rdr2-desc1.jpg",
      "/images/rdr2-desc2.jpg",
      "/images/rdr2-desc3.jpg",
      "/images/rdr2-desc4.jpg",
    ],
  },
  {
    id: "game-4",
    title: "FIFA 23",
    description: "Experience the world's game with over 19,000 players, 700+ teams, 100+ stadiums, and 30+ leagues.",
    image: "/images/fifa23.jpg",
    price: 69.99,
    discount: 35,
    platform: "Origin",
    category: "games",
    publisher: "Electronic Arts",
    releaseDate: "2022-09-30",
    genres: ["Sports", "Simulation"],
    rating: 4.2,
    sales: 10000000,
    features: ["Multiplayer", "Controller Support", "Online Competitive"],
    images: [
      "/images/fifa23.jpg",
      "/images/fifa23-desc1.jpg",
      "/images/fifa23-desc2.jpg",
      "/images/fifa23-desc3.jpg",
      "/images/fifa23-desc4.jpg",
    ],
  },
  {
    id: "game-5",
    title: "The Witcher 3: Wild Hunt",
    description: "A story-driven, open world adventure set in a dark fantasy universe.",
    image: "/images/witcher3.jpg",
    price: 39.99,
    discount: 70,
    platform: "Steam",
    category: "games",
    publisher: "CD Projekt RED",
    releaseDate: "2015-05-19",
    genres: ["RPG", "Open World", "Fantasy"],
    rating: 4.9,
    sales: 40000000,
    features: ["Open World", "Story Rich", "Atmospheric"],
    images: [
      "/images/witcher3.jpg",
      "/images/witcher3-desc1.jpg",
      "/images/witcher3-desc2.jpg",
      "/images/witcher3-desc3.jpg",
      "/images/witcher3-desc4.jpg",
    ],
  },
  {
    id: "game-6",
    title: "Battlefield 2042",
    description: "A first-person shooter that marks the return to the iconic all-out warfare of the franchise.",
    image: "/images/battlefield2042.jpg",
    price: 59.99,
    discount: 60,
    platform: "Origin",
    category: "games",
    publisher: "Electronic Arts",
    releaseDate: "2021-11-19",
    genres: ["FPS", "Action", "Multiplayer"],
    rating: 3.2,
    sales: 4500000,
    features: ["Multiplayer", "FPS", "Action"],
    images: [
      "/images/battlefield2042.jpg",
      "/images/battlefield2042desc1.jpeg",
      "/images/battlefielddesc2.jpeg",
      "/images/battlefielddesc3.jpeg",
      "/images/battlefielddesc4.jpeg",
    ],
  },
  {
    id: "game-7",
    title: "Hollow Knight",
    description:
      "A challenging 2D action-adventure. Explore twisting caverns, battle tainted creatures and escape intricate traps.",
    image: "/images/hollowknight.jpg",
    price: 14.99,
    discount: 50,
    platform: "Steam",
    category: "games",
    publisher: "Team Cherry",
    releaseDate: "2017-02-24",
    genres: ["Metroidvania", "Indie", "Action"],
    rating: 4.9,
    sales: 3000000,
    features: ["Atmospheric", "Difficult", "Great Soundtrack"],
    images: [
      "/images/hollowknight.jpg",
      "/images/hollowknight-desc1.jpg",
      "/images/hollowknight-desc2.jpg",
      "/images/hollowknight-desc3.jpg",
      "/images/hollowknight-desc4.jpg",
    ],
  },
  {
    id: "game-8",
    title: "Hades",
    description:
      "A god-like rogue-like dungeon crawler that combines the best aspects of Supergiant's critically acclaimed titles.",
    image: "/images/hades.jpg",
    price: 24.99,
    discount: 30,
    platform: "Epic Games",
    category: "games",
    publisher: "Supergiant Games",
    releaseDate: "2020-09-17",
    genres: ["Roguelike", "Indie", "Action"],
    rating: 4.8,
    sales: 1000000,
    features: ["Great Soundtrack", "Action Roguelike", "Story Rich"],
    images: [
      "/images/hades.jpg",
      "/images/hades-desc1.jpg",
      "/images/hades-desc2.jpg",
      "/images/hades-desc3.jpg",
      "/images/hades-desc4.jpg",
    ],
  },
  {
    id: "software-1",
    title: "Microsoft Office 2023",
    description: "The latest version of Microsoft Office with Word, Excel, PowerPoint, and more.",
    image: "/images/microsoftoffice.png",
    price: 149.99,
    discount: 20,
    platform: "Windows",
    category: "software",
    publisher: "Microsoft",
    releaseDate: "2022-10-05",
    genres: ["Productivity", "Business"],
    rating: 4.5,
    sales: 8000000,
    features: ["Word Processing", "Spreadsheets", "Presentations"],
    images: [
      "/images/microsoftoffice.png",
      "/images/microsoftoffice-desc1.jpg",
      "/images/microsoftoffice-desc2.jpg",
      "/images/microsoftoffice-desc3.jpg",
      "/images/microsoftoffice-desc4.jpg",
    ],
  },
  {
    id: "software-2",
    title: "Adobe Creative Cloud",
    description:
      "A collection of 20+ desktop and mobile apps and services for photography, design, video, web, UX, and more.",
    image: "/images/adobecreativecloud.jpg",
    price: 52.99,
    discount: 15,
    platform: "Cross-platform",
    category: "software",
    publisher: "Adobe",
    releaseDate: "2022-01-15",
    genres: ["Creative", "Design", "Photography"],
    rating: 4.7,
    sales: 5000000,
    features: ["Photoshop", "Illustrator", "Premiere Pro"],
    images: [
      "/images/adobecreativecloud.jpg",
      "/images/adobecreativecloud-desc1.jpg",
      "/images/adobecreativecloud-desc2.jpg",
      "/images/adobecreativecloud-desc3.jpg",
      "/images/adobecreativecloud-desc4.jpg",
    ],
  },
  {
    id: "software-3",
    title: "Windows 11 Pro",
    description: "The latest version of Windows with advanced security and management features.",
    image: "/images/windows11.jpg",
    price: 199.99,
    discount: 10,
    platform: "Windows",
    category: "software",
    publisher: "Microsoft",
    releaseDate: "2021-10-05",
    genres: ["Operating System", "Productivity"],
    rating: 4.3,
    sales: 20000000,
    features: ["Enhanced Security", "Virtual Desktops", "Microsoft Store"],
    images: [
      "/images/windows11.jpg",
      "/images/windows11-desc1.jpg",
      "/images/windows11-desc2.jpg",
      "/images/windows11-desc3.jpg",
      "/images/windows11-desc4.jpg",
    ],
  },
  {
    id: "software-4",
    title: "Autodesk Maya 2023",
    description: "3D animation, modeling, simulation, and rendering software for film, TV, and games.",
    image: "/placeholder.svg?height=300&width=300&text=Maya+2023",
    price: 205.0,
    discount: 25,
    platform: "Windows/Mac",
    category: "software",
    publisher: "Autodesk",
    releaseDate: "2022-03-29",
    genres: ["3D Modeling", "Animation", "Design"],
    rating: 4.6,
    sales: 1000000,
    features: ["3D Modeling", "Animation", "Visual Effects"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Maya+2023",
      "/placeholder.svg?height=300&width=300&text=Maya+2023",
      "/placeholder.svg?height=300&width=300&text=Maya+2023",
      "/placeholder.svg?height=300&width=300&text=Maya+2023",
    ],
  },
  {
    id: "software-5",
    title: "Norton 360 Deluxe",
    description: "Comprehensive protection for your devices and online privacy.",
    image: "/placeholder.svg?height=300&width=300&text=Norton+360",
    price: 89.99,
    discount: 50,
    platform: "Cross-platform",
    category: "software",
    publisher: "NortonLifeLock",
    releaseDate: "2022-05-17",
    genres: ["Security", "Antivirus"],
    rating: 4.2,
    sales: 3000000,
    features: ["Real-time Protection", "VPN", "Password Manager"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Norton+360",
      "/placeholder.svg?height=300&width=300&text=Norton+360",
      "/placeholder.svg?height=300&width=300&text=Norton+360",
      "/placeholder.svg?height=300&width=300&text=Norton+360",
    ],
  },
  {
    id: "digital-1",
    title: "Steam Wallet $50",
    description: "Add funds to your Steam Wallet to purchase games, software, and more on Steam.",
    image: "/placeholder.svg?height=300&width=300&text=Steam+Wallet",
    price: 50.0,
    discount: 5,
    platform: "Steam",
    category: "digital",
    publisher: "Valve",
    releaseDate: "2023-01-01",
    genres: ["Gift Card", "Digital Currency"],
    rating: 4.9,
    sales: 15000000,
    features: ["Instant Delivery", "No Expiration", "Global Usage"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Steam+Wallet",
      "/placeholder.svg?height=300&width=300&text=Steam+Wallet",
      "/placeholder.svg?height=300&width=300&text=Steam+Wallet",
      "/placeholder.svg?height=300&width=300&text=Steam+Wallet",
    ],
  },
  {
    id: "digital-2",
    title: "Xbox Game Pass Ultimate (3 Months)",
    description: "Get unlimited access to over 100 high-quality games on console, PC, and cloud.",
    image: "/placeholder.svg?height=300&width=300&text=Game+Pass",
    price: 44.99,
    discount: 30,
    platform: "Xbox",
    category: "digital",
    publisher: "Microsoft",
    releaseDate: "2023-01-01",
    genres: ["Subscription", "Gaming Service"],
    rating: 4.8,
    sales: 10000000,
    features: ["Xbox Live Gold", "EA Play", "Cloud Gaming"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Game+Pass",
      "/placeholder.svg?height=300&width=300&text=Game+Pass",
      "/placeholder.svg?height=300&width=300&text=Game+Pass",
      "/placeholder.svg?height=300&width=300&text=Game+Pass",
    ],
  },
  {
    id: "digital-3",
    title: "PlayStation Plus (12 Months)",
    description:
      "Enhance your PlayStation experience with online multiplayer, monthly games, exclusive discounts, and more.",
    image: "/placeholder.svg?height=300&width=300&text=PS+Plus",
    price: 59.99,
    discount: 20,
    platform: "PlayStation",
    category: "digital",
    publisher: "Sony",
    releaseDate: "2023-01-01",
    genres: ["Subscription", "Gaming Service"],
    rating: 4.7,
    sales: 9000000,
    features: ["Online Multiplayer", "Monthly Games", "Exclusive Discounts"],
    images: [
      "/placeholder.svg?height=300&width=300&text=PS+Plus",
      "/placeholder.svg?height=300&width=300&text=PS+Plus",
      "/placeholder.svg?height=300&width=300&text=PS+Plus",
      "/placeholder.svg?height=300&width=300&text=PS+Plus",
    ],
  },
  {
    id: "digital-4",
    title: "Spotify Premium (12 Months)",
    description: "Ad-free music listening, offline playback, and on-demand playback.",
    image: "/placeholder.svg?height=300&width=300&text=Spotify",
    price: 99.99,
    discount: 15,
    platform: "Cross-platform",
    category: "digital",
    publisher: "Spotify",
    releaseDate: "2023-01-01",
    genres: ["Subscription", "Music Service"],
    rating: 4.6,
    sales: 20000000,
    features: ["Ad-free", "Offline Listening", "High Quality Audio"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Spotify",
      "/placeholder.svg?height=300&width=300&text=Spotify",
      "/placeholder.svg?height=300&width=300&text=Spotify",
      "/placeholder.svg?height=300&width=300&text=Spotify",
    ],
  },
  {
    id: "digital-5",
    title: "Netflix Gift Card $50",
    description: "Give the gift of unlimited entertainment with a Netflix gift card.",
    image: "/placeholder.svg?height=300&width=300&text=Netflix",
    price: 50.0,
    discount: 0,
    platform: "Cross-platform",
    category: "digital",
    publisher: "Netflix",
    releaseDate: "2023-01-01",
    genres: ["Gift Card", "Streaming Service"],
    rating: 4.5,
    sales: 25000000,
    features: ["Instant Delivery", "No Expiration", "Global Usage"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Netflix",
      "/placeholder.svg?height=300&width=300&text=Netflix",
      "/placeholder.svg?height=300&width=300&text=Netflix",
      "/placeholder.svg?height=300&width=300&text=Netflix",
    ],
  },
  {
    id: "digital-6",
    title: "Roblox Gift Card $25",
    description: "Get Robux to purchase avatars, accessories, and more in Roblox.",
    image: "/placeholder.svg?height=300&width=300&text=Roblox",
    price: 25.0,
    discount: 0,
    platform: "Cross-platform",
    category: "digital",
    publisher: "Roblox Corporation",
    releaseDate: "2023-01-01",
    genres: ["Gift Card", "Gaming Currency"],
    rating: 4.7,
    sales: 30000000,
    features: ["Instant Delivery", "No Expiration", "Global Usage"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Roblox",
      "/placeholder.svg?height=300&width=300&text=Roblox",
      "/placeholder.svg?height=300&width=300&text=Roblox",
      "/placeholder.svg?height=300&width=300&text=Roblox",
    ],
  },
  // New games
  {
    id: "game-11",
    title: "God of War Ragnarök",
    description: "Embark on a mythic journey for answers and allies before Ragnarök arrives.",
    image: "/placeholder.svg?height=300&width=300&text=God+of+War",
    price: 69.99,
    discount: 15,
    platform: "PlayStation",
    category: "games",
    publisher: "Sony Interactive Entertainment",
    releaseDate: "2022-11-09",
    genres: ["Action", "Adventure"],
    rating: 4.9,
    sales: 5200000,
    features: ["Story Rich", "Action", "Single-player"],
    images: [
      "/placeholder.svg?height=300&width=300&text=God+of+War",
      "/placeholder.svg?height=300&width=300&text=God+of+War",
      "/placeholder.svg?height=300&width=300&text=God+of+War",
      "/placeholder.svg?height=300&width=300&text=God+of+War",
    ],
  },
  {
    id: "game-12",
    title: "Horizon Forbidden West",
    description: "Join Aloy as she braves the Forbidden West, a deadly frontier that conceals mysterious new threats.",
    image: "/placeholder.svg?height=300&width=300&text=Horizon",
    price: 59.99,
    discount: 25,
    platform: "PlayStation",
    category: "games",
    publisher: "Sony Interactive Entertainment",
    releaseDate: "2022-02-18",
    genres: ["Action", "RPG", "Open World"],
    rating: 4.7,
    sales: 8300000,
    features: ["Open World", "Female Protagonist", "Story Rich"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Horizon",
      "/placeholder.svg?height=300&width=300&text=Horizon",
      "/placeholder.svg?height=300&width=300&text=Horizon",
      "/placeholder.svg?height=300&width=300&text=Horizon",
    ],
  },
  {
    id: "game-13",
    title: "Forza Horizon 5",
    description: "Your Ultimate Horizon Adventure awaits! Explore the vibrant open world landscapes of Mexico.",
    image: "/placeholder.svg?height=300&width=300&text=Forza+Horizon+5",
    price: 59.99,
    discount: 30,
    platform: "Xbox/PC",
    category: "games",
    publisher: "Xbox Game Studios",
    releaseDate: "2021-11-09",
    genres: ["Racing", "Open World"],
    rating: 4.8,
    sales: 10000000,
    features: ["Open World", "Multiplayer", "Realistic"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Forza+Horizon+5",
      "/placeholder.svg?height=300&width=300&text=Forza+Horizon+5",
      "/placeholder.svg?height=300&width=300&text=Forza+Horizon+5",
      "/placeholder.svg?height=300&width=300&text=Forza+Horizon+5",
    ],
  },
  {
    id: "game-14",
    title: "Resident Evil Village",
    description:
      "Experience survival horror like never before in the 8th major installment in the Resident Evil franchise.",
    image: "/capcomlogo.png",
    price: 49.99,
    discount: 40,
    platform: "Multiple",
    category: "games",
    publisher: "Capcom",
    releaseDate: "2021-05-07",
    genres: ["Horror", "Survival", "First-Person"],
    rating: 4.6,
    sales: 6500000,
    features: ["Horror", "First-Person", "Story Rich"],
    images: ["/capcomlogo.png", "/capcomlogo.png", "/capcomlogo.png", "/capcomlogo.png"],
  },
  {
    id: "game-15",
    title: "Final Fantasy XVI",
    description: "The latest installment in the legendary RPG series, featuring a dark fantasy setting.",
    image: "/placeholder.svg?height=300&width=300&text=FF+XVI",
    price: 69.99,
    discount: 0,
    platform: "PlayStation",
    category: "games",
    publisher: "Square Enix",
    releaseDate: "2023-06-22",
    genres: ["RPG", "Action", "Fantasy"],
    rating: 4.7,
    sales: 3000000,
    features: ["Story Rich", "Fantasy", "Action Combat"],
    images: [
      "/placeholder.svg?height=300&width=300&text=FF+XVI",
      "/placeholder.svg?height=300&width=300&text=FF+XVI",
      "/placeholder.svg?height=300&width=300&text=FF+XVI",
      "/placeholder.svg?height=300&width=300&text=FF+XVI",
    ],
  },
  // New software
  {
    id: "software-7",
    title: "Affinity Designer 2",
    description: "Professional graphic design software with no subscription.",
    image: "/affinitydesigner2.jpg",
    price: 69.99,
    discount: 20,
    platform: "Cross-platform",
    category: "software",
    publisher: "Serif",
    releaseDate: "2022-11-09",
    genres: ["Design", "Vector Graphics"],
    rating: 4.8,
    sales: 1500000,
    features: ["Vector Design", "No Subscription", "Professional Tools"],
    images: ["/affinitydesigner2.jpg", "/affinitydesigner2.jpg", "/affinitydesigner2.jpg", "/affinitydesigner2.jpg"],
  },
  {
    id: "software-8",
    title: "DaVinci Resolve Studio",
    description: "Professional video editing, color correction, visual effects, and audio post-production.",
    image: "/placeholder.svg?height=300&width=300&text=DaVinci+Resolve",
    price: 295.0,
    discount: 0,
    platform: "Cross-platform",
    category: "software",
    publisher: "Blackmagic Design",
    releaseDate: "2022-08-23",
    genres: ["Video Editing", "Color Grading"],
    rating: 4.9,
    sales: 2000000,
    features: ["8K Support", "Color Grading", "Audio Post"],
    images: [
      "/placeholder.svg?height=300&width=300&text=DaVinci+Resolve",
      "/placeholder.svg?height=300&width=300&text=DaVinci+Resolve",
      "/placeholder.svg?height=300&width=300&text=DaVinci+Resolve",
      "/placeholder.svg?height=300&width=300&text=DaVinci+Resolve",
    ],
  },
  // New digital products
  {
    id: "digital-7",
    title: "Disney+ (12 Months)",
    description: "Stream exclusive Disney originals, movies, shows, and more.",
    image: "/placeholder.svg?height=300&width=300&text=Disney+",
    price: 79.99,
    discount: 15,
    platform: "Cross-platform",
    category: "digital",
    publisher: "Disney",
    releaseDate: "2023-01-01",
    genres: ["Subscription", "Streaming Service"],
    rating: 4.6,
    sales: 15000000,
    features: ["4K Streaming", "Family Content", "Original Shows"],
    images: [
      "/placeholder.svg?height=300&width=300&text=Disney+",
      "/placeholder.svg?height=300&width=300&text=Disney+",
      "/placeholder.svg?height=300&width=300&text=Disney+",
      "/placeholder.svg?height=300&width=300&text=Disney+",
    ],
  },
  {
    id: "digital-8",
    title: "Amazon Gift Card $100",
    description: "Shop millions of products on Amazon with this gift card.",
    image: "/amazon100.png",
    price: 100.0,
    discount: 0,
    platform: "Cross-platform",
    category: "digital",
    publisher: "Amazon",
    releaseDate: "2023-01-01",
    genres: ["Gift Card", "Shopping"],
    rating: 4.9,
    sales: 50000000,
    features: ["Instant Delivery", "No Expiration", "Global Usage"],
    images: ["/amazon100.png", "/amazon100.png", "/amazon100.png", "/amazon100.png"],
  },
]

// Mock publisher data
export const mockPublishers = [
  {
    id: "publisher-1",
    name: "Electronic Arts",
    logo: "/placeholder.svg?height=200&width=200&text=EA",
    description:
      "Electronic Arts Inc. is an American video game company headquartered in Redwood City, California. It is the second-largest gaming company in the Americas and Europe by revenue and market capitalization after Activision Blizzard and ahead of Take-Two Interactive, CD Projekt, and Ubisoft as of May 2020.",
    founded: "1982",
    headquarters: "Redwood City, California, USA",
    website: "https://www.ea.com",
    products: ["FIFA", "Battlefield", "The Sims", "Apex Legends", "Mass Effect"],
    featuredProducts: [
      {
        id: "game-4",
        title: "FIFA 23",
        image: "/placeholder.svg?height=300&width=300&text=FIFA+23",
        discount: 35,
      },
      {
        id: "game-6",
        title: "Battlefield 2042",
        image: "/images/battlefield2042.jpg",
        discount: 60,
      },
      {
        id: "game-9",
        title: "The Sims 4",
        image: "/placeholder.svg?height=300&width=300&text=Sims+4",
        discount: 75,
      },
    ],
  },
  {
    id: "publisher-2",
    name: "Microsoft",
    logo: "/placeholder.svg?height=200&width=200&text=Microsoft",
    description:
      "Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services.",
    founded: "1975",
    headquarters: "Redmond, Washington, USA",
    website: "https://www.microsoft.com",
    products: ["Windows", "Office", "Xbox", "Surface", "Azure"],
    featuredProducts: [
      {
        id: "software-1",
        title: "Microsoft Office 2023",
        image: "/images/microsoftoffice.png",
        discount: 20,
      },
      {
        id: "software-3",
        title: "Windows 11 Pro",
        image: "/placeholder.svg?height=300&width=300&text=Windows+11",
        discount: 10,
      },
      {
        id: "digital-2",
        title: "Xbox Game Pass Ultimate (3 Months)",
        image: "/placeholder.svg?height=300&width=300&text=Game+Pass",
        discount: 30,
      },
    ],
  },
  {
    id: "publisher-3",
    name: "CD Projekt RED",
    logo: "/placeholder.svg?height=200&width=200&text=CDPR",
    description:
      "CD Projekt S.A. is a Polish video game developer, publisher and distributor based in Warsaw, founded in May 1994 by Marcin Iwiński and Michał Kiciński.",
    founded: "1994",
    headquarters: "Warsaw, Poland",
    website: "https://www.cdprojekt.com",
    products: ["The Witcher", "Cyberpunk 2077", "GWENT"],
    featuredProducts: [
      {
        id: "game-2",
        title: "Cyberpunk 2077",
        image: "/images/cyberpunk.png",
        discount: 50,
      },
      {
        id: "game-5",
        title: "The Witcher 3: Wild Hunt",
        image: "/placeholder.svg?height=300&width=300&text=Witcher+3",
        discount: 70,
      },
    ],
  },
  {
    id: "publisher-4",
    name: "Adobe",
    logo: "/images/adobelogo.png",
    description:
      "Adobe Inc. is an American multinational computer software company. It has historically focused upon the creation of multimedia and creativity software products.",
    founded: "1982",
    headquarters: "San Jose, California, USA",
    website: "https://www.adobe.com",
    products: ["Photoshop", "Illustrator", "Premiere Pro", "After Effects", "Acrobat"],
    featuredProducts: [
      {
        id: "software-2",
        title: "Adobe Creative Cloud",
        image: "/images/adobecreativecloud.jpg",
        discount: 15,
      },
    ],
  },
  {
    id: "publisher-5",
    name: "Valve",
    logo: "/placeholder.svg?height=200&width=200&text=Valve",
    description:
      "Valve Corporation is an American video game developer, publisher, and digital distribution company headquartered in Bellevue, Washington.",
    founded: "1996",
    headquarters: "Bellevue, Washington, USA",
    products: ["Half-Life", "Counter-Strike", "Portal", "Dota 2", "Steam"],
    featuredProducts: [
      {
        id: "digital-1",
        title: "Steam Wallet $50",
        image: "/placeholder.svg?height=300&width=300&text=Steam+Wallet",
        discount: 5,
      },
    ],
  },
  {
    id: "publisher-6",
    name: "Sony Interactive Entertainment",
    logo: "/placeholder.svg?height=200&width=200&text=Sony",
    description:
      "Sony Interactive Entertainment is a multinational video game and digital entertainment company owned by Sony Group Corporation.",
    founded: "1993",
    headquarters: "San Mateo, California, USA",
    website: "https://www.sie.com",
    products: ["PlayStation", "God of War", "Horizon", "The Last of Us", "Uncharted"],
    featuredProducts: [
      {
        id: "game-11",
        title: "God of War Ragnarök",
        image: "/placeholder.svg?height=300&width=300&text=God+of+War",
        discount: 15,
      },
      {
        id: "game-12",
        title: "Horizon Forbidden West",
        image: "/placeholder.svg?height=300&width=300&text=Horizon",
        discount: 25,
      },
      {
        id: "digital-3",
        title: "PlayStation Plus (12 Months)",
        image: "/placeholder.svg?height=300&width=300&text=PS+Plus",
        discount: 20,
      },
    ],
  },
  {
    id: "publisher-7",
    name: "Square Enix",
    logo: "/placeholder.svg?height=200&width=200&text=Square+Enix",
    description:
      "Square Enix Holdings Co., Ltd. is a Japanese entertainment conglomerate and video game company best known for its Final Fantasy, Dragon Quest, and Kingdom Hearts franchises.",
    founded: "2003",
    headquarters: "Tokyo, Japan",
    website: "https://www.square-enix.com",
    products: ["Final Fantasy", "Dragon Quest", "Kingdom Hearts", "Tomb Raider", "Nier"],
    featuredProducts: [
      {
        id: "game-15",
        title: "Final Fantasy XVI",
        image: "/placeholder.svg?height=300&width=300&text=FF+XVI",
        discount: 0,
      },
    ],
  },
  {
    id: "publisher-8",
    name: "Capcom",
    logo: "/capcomlogo.png",
    description:
      "Capcom Co., Ltd. is a Japanese video game developer and publisher known for creating numerous multi-million selling game franchises.",
    founded: "1979",
    headquarters: "Osaka, Japan",
    website: "https://www.capcom.com",
    products: ["Resident Evil", "Monster Hunter", "Street Fighter", "Devil May Cry", "Mega Man"],
    featuredProducts: [
      {
        id: "game-14",
        title: "Resident Evil Village",
        image: "/capcomlogo.png",
        discount: 40,
      },
    ],
  },
  {
    id: "publisher-9",
    name: "Bandai Namco",
    logo: "/bandainamco.png",
    description:
      "Bandai Namco Entertainment Inc. is a Japanese multinational video game publisher and developer, and the video game arm of Bandai Namco Holdings.",
    founded: "2006",
    headquarters: "Tokyo, Japan",
    website: "https://www.bandainamco.com",
    products: ["Elden Ring", "Dark Souls", "Tekken", "Pac-Man", "Dragon Ball"],
    featuredProducts: [
      {
        id: "game-1",
        title: "Elden Ring",
        image: "/images/elden.png",
        discount: 25,
      },
    ],
  },
]

// Mock user data
export const mockUsers = [
  {
    id: "user-1",
    name: "John Doe",
    email: "john@example.com",
    avatar: "/placeholder.svg?height=100&width=100&text=JD",
    password: "password123", // In a real app, this would be properly hashed
    wishlist: ["game-1", "software-2", "digital-3"],
    cart: ["game-4", "software-1"],
    orders: [
      {
        id: "order-1",
        date: "2023-03-15",
        total: 59.99,
        status: "completed",
        items: [
          {
            id: "game-5",
            title: "The Witcher 3: Wild Hunt",
            price: 39.99,
            discount: 70,
            platform: "Steam",
          },
        ],
      },
      {
        id: "order-2",
        date: "2023-02-28",
        total: 149.99,
        status: "completed",
        items: [
          {
            id: "software-1",
            title: "Microsoft Office 2023",
            price: 149.99,
            discount: 20,
            platform: "Windows",
          },
        ],
      },
    ],
    settings: {
      notifications: true,
      newsletter: false,
      darkMode: false,
    },
  },
  {
    id: "user-2",
    name: "Jane Smith",
    email: "jane@example.com",
    avatar: "/placeholder.svg?height=100&width=100&text=JS",
    password: "password123", // In a real app, this would be properly hashed
    wishlist: ["game-2", "game-11", "digital-7"],
    cart: [],
    orders: [
      {
        id: "order-3",
        date: "2023-04-10",
        total: 89.99,
        status: "completed",
        items: [
          {
            id: "game-11",
            title: "God of War Ragnarök",
            price: 69.99,
            discount: 15,
            platform: "PlayStation",
          },
        ],
      },
    ],
    settings: {
      notifications: true,
      newsletter: true,
      darkMode: true,
    },
  },
]
